
SELECT TO_DATE('25-12', 'dd-mm') FROM DUAL;
SELECT TO_DATE('25', 'dd') FROM DUAL;

SELECT TO_DATE('18', 'yy') FROM DUAL;
SELECT TO_DATE('12','mm') FROM DUAL;
SELECT TO_DATE('12-DECEMBER-2018 at 12:00:00 AM','dd-MONTH-YYYY "at" HH:MI:SS AM') FROM DUAL;

SELECT TO_DATE('January 15, 1989, 11:00 A.M.','Month dd, YYYY, HH:MI A.M.','NLS_DATE_LANGUAGE = American')FROM DUAL;

SELECT TO_TIMESTAMP ('10-Sep-02 14:10:10.123000', 'DD-Mon-RR HH24:MI:SS.FF')
   FROM DUAL;
   
   SELECT 10 + 10 FROM DUAL;
   SELECT '+10 12:20:00' + '+0 12:00:00' FROM DUAL;
   
SELECT TO_DSINTERVAL('+10 12:30:25') + TO_DSINTERVAL('+0 12:30:25')
    FROM DUAL;
    
SELECT TO_YMINTERVAL('01-02') "14 months"
   FROM DUAL;
   
SELECT HIREDATE, HIREDATE + TO_YMINTERVAL('01-02') "14 months"
   FROM EMP;
   
SELECT SYS_EXTRACT_UTC(TIMESTAMP '2000-03-28 11:30:00.00 -0:00')
   FROM DUAL;

SELECT FROM_TZ(TIMESTAMP '2000-03-28 08:00:00', '3:00') 
   FROM DUAL;
   
SELECT TZ_OFFSET('US/Eastern') FROM DUAL;

SELECT TZ_OFFSET('Europe/London') FROM DUAL;

SELECT TZ_OFFSET('Asia/Calcutta') FROM DUAL;

SELECT SESSIONTIMEZONE FROM DUAL;

SELECT * FROM EMP;

SELECT DEPTNO FROM EMP;

SELECT ALL Deptno FROM EMP;

SELECT DISTINCT Deptno FROM EMP;

SELECT JOB FROM EMP;

SELECT DISTINCT JOB FROM EMP;

SELECT COUNT(*) FROM EMP;

SELECT DEPTNO,JOB, COUNT(*) FROM EMP GROUP BY DEPTNO, JOB;

SELECT SUM(SAL) FROM EMP;

SELECT DEPTNO,SUM(SAL) FROM EMP GROUP BY DEPTNO;

SELECT DEPTNO,SUM(SAL) FROM EMP GROUP BY DEPTNO HAVING DEPTNO=10;

SELECT DEPTNO, JOB,COUNT(*), SUM(SAL) FROM EMP GROUP BY DEPTNO, JOB;

SELECT DEPTNO, JOB,COUNT(*), SUM(SAL) FROM EMP GROUP BY DEPTNO, JOB HAVING JOB='CLERK';

SELECT DEPTNO, JOB,COUNT(*), SUM(SAL) FROM EMP GROUP BY DEPTNO, JOB HAVING JOB='CLERK' ORDER BY DEPTNO;

SELECT AVG(SAL) FROM EMP;

SELECT DEPTNO, AVG(SAL) FROM EMP GROUP BY DEPTNO;

SELECT DEPTNO,JOB, AVG(SAL) FROM EMP GROUP BY DEPTNO,JOB;

SELECT DEPTNO,JOB, AVG(SAL) FROM EMP GROUP BY DEPTNO,JOB HAVING JOB= 'CLERK';

SELECT MIN(SAL) FROM EMP;

SELECT MAX(SAL) FROM EMP;

SELECT DEPTNO,MIN(SAL) FROM EMP GROUP BY DEPTNO;

SELECT DEPTNO,MAX(SAL) FROM EMP GROUP BY DEPTNO;